# Generated by Django 5.2.1 on 2025-05-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_city_delete_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('city', models.CharField(max_length=100)),
                ('yandex_city_id', models.CharField(max_length=50)),
                ('count', models.PositiveIntegerField(default=1)),
                ('last_search', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'История поиска',
                'verbose_name_plural': 'Истории поиска',
                'ordering': ['-last_search'],
                'unique_together': {('session_key', 'yandex_city_id')},
            },
        ),
        migrations.DeleteModel(
            name='City',
        ),
    ]
