# Generated by Django 5.2.1 on 2025-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_searchhistory_delete_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'verbose_name': 'История поиска', 'verbose_name_plural': 'Истории поиска'},
        ),
        migrations.AlterUniqueTogether(
            name='searchhistory',
            unique_together={('city',)},
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='last_searched',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний запрос'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='search_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество запросов'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='count',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='last_search',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='searchhistory',
            name='yandex_city_id',
        ),
    ]
