# Generated by Django 5.2.1 on 2025-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0004_alter_searchhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-last_searched'], 'verbose_name': 'Запись истории поиска', 'verbose_name_plural': 'История поисковых запросов'},
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Название населенного пункта'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='last_searched',
            field=models.DateTimeField(auto_now=True, verbose_name='Последний поиск'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['city'], name='weather_app_city_fe6ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['last_searched'], name='weather_app_last_se_c34bfb_idx'),
        ),
    ]
